[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "manim-fa-physics"
version = "0.2.0"
description = "افزونه فیزیک برای Manim (مکانیک، گرانش، اوپتیک، الکترومغناطیس، الکترواستاتیک، موج)"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "علی تابش", email = "tabesh_ali@yahoo.com" }
]
dependencies = [
    "manim>=0.19.0",
    "numpy>=1.24",
    "pymunk>=6.0.0",
    "shapely>=2.0.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics",
]

[project.urls]
Homepage = "https://github.com/Tabesh2020/manim-fa-physics"
Repository = "https://github.com/Tabesh2020/manim-fa-physics"

[tool.setuptools.packages.find]
where = ["."]
include = ["manim_fa_physics*"]
